# f1datalab/Dockerfile.frontend_prod

FROM node:20-alpine as builder
WORKDIR /app


ARG NEXT_PUBLIC_BACKEND_URL


ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

COPY package.json ./
COPY package-lock.json ./

RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine as runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

COPY package.json ./
RUN npm install --only=production


RUN chmod -R a+rX /app/.next \
    && chmod -R a+rX /app/public


EXPOSE 3000
CMD ["npm", "start"]