# version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_BACKEND_URL_ARG=http://backend:8888 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
  backend:
    build:
      context: ./f1backend
      dockerfile: Dockerfile.backend
    ports:
      - "8888:8888"
    volumes:
      - ./f1backend:/app
    environment:
      - RUN_MODE=container
      - DATABASE_URL=mysql://root:123@mysql:3306/f1db
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: f1db
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./database/f1db.sql:/docker-entrypoint-initdb.d/f1db.sql
    ports:
      - "3306:3306"


  # dbgate:
  #   image: dbgate/dbgate
  #   restart: always
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - dbgate-data:/root/.dbgate
  #   environment:
  #     CONNECTIONS: con1
  #     LABEL_con1: MySql
  #     SERVER_con1: mysql
  #     USER_con1: root
  #     PASSWORD_con1: 123
  #     PORT_con1: 3306
  #     ENGINE_con1: mysql@dbgate-plugin-mysql
 
volumes:
  dbgate-data:
    driver: local