FROM node:20-alpine
WORKDIR /app
ARG REACT_APP_BACKEND_URL_ARG=http://localhost:8888
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL_ARG}
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]