# f1datalab/Dockerfile.frontend_prod

# --- Stage 1: Build the Next.js application ---
FROM node:20-alpine as builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./

RUN npm install
COPY . .
RUN npm run build

# --- Stage 2: Create the production Next.js server image ---
FROM node:20-alpine as runner
WORKDIR /app

# ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

COPY package.json ./
RUN npm install --only=production


RUN chmod -R a+rX /app/.next \
    && chmod -R a+rX /app/public


EXPOSE 3000
CMD ["npm", "start"]