
FROM docker.io/library/node:20-alpine AS frontend
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

FROM nginx:stable-alpine


COPY --from=frontend /app/.next/static /app/.next/static
COPY --from=frontend /app/public /app/public