import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
export const driverColors: { [key: string]: string } = {
  max_verstappen: "#3671C6",
  perez: "#3671C6",
  hamilton: "#00D2BE",
  russell: "#00D2BE",
  leclerc: "#DC0000",
  sainz: "#DC0000",
  norris: "#FF8700",
  piastri: "#FF8700",
  alonso: "#0090FF",
  stroll: "#0090FF",
  gasly: "#005AFF",
  ocon: "#005AFF",
  tsunoda: "#2B4562",
  ricciardo: "#2B4562",
  bottas: "#B6BABD",
  zhou: "#B6BABD",
  hulkenberg: "#B6BABD",
  magnussen: "#B6BABD",
  albon: "#0092DA",
  sargeant: "#0092DA",
  vettel: "#0090FF",
  raikkonen: "#B6BABD",
  latifi: "#0092DA",
  schumacher: "#B6BABD",
  de_vries: "#2B4562",
  kubica: "#B6BABD",
  giovinazzi: "#B6BABD",
  kvyat: "#2B4562",
  grosjean: "#B6BABD",
};

export const nationalityToFlag: { [key: string]: string } = {
  British: "gb",
  Dutch: "nl",
  German: "de",
  Monegasque: "mc",
  Finnish: "fi",
  Australian: "au",
  Mexican: "mx",
  UnitedStates: "us",
  French: "fr",
  Spanish: "es",
  Canadian: "ca",
  Polish: "pl",
  Japanese: "jp",
  Thai: "th",
  Danish: "dk",
  Chinese: "cn",
  "New Zealander": "nz",
  Russian: "ru",
  Italian: "it",
  Brazilian: "br",
  Indian: "in",
  Swiss: "ch",
  Austrian: "at",
  Belgian: "be",
  Swedish: "se",
  SouthAfrican: "za",
  American: "us"
};